USE [BD_RCPDOC]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.T_Tramite (
    iCod_tramite INT IDENTITY(1,1) NOT NULL,
    iCodTipoPer INT NOT NULL,
    iCodAsunto INT NOT NULL,
    vRUC NCHAR(11) NULL,
    CONSTRAINT PK_T_Tramite PRIMARY KEY CLUSTERED (iCod_tramite)
);