USE [SISGED];
GO

IF OBJECT_ID(N'dbo.USP_TIPO_DOCUMENTO_LISTAR', N'P') IS NOT NULL
    DROP PROCEDURE dbo.USP_TIPO_DOCUMENTO_LISTAR;
GO

CREATE PROCEDURE dbo.USP_TIPO_DOCUMENTO_LISTAR
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        IDE_TIPO_DOCUMENTO AS iCodTipoDoc,
        LTRIM(RTRIM(TXT_NOM_CORTO)) AS vNombreTipoDoc
    FROM dbo.GED_TG_TIPO_DOCUMENTO
    WHERE ISNULL(FLG_REGISTRO, 0) = 1
      AND ISNULL(FLG_EXT, 0) = 1
      AND TXT_NOM_CORTO IS NOT NULL
      AND LTRIM(RTRIM(TXT_NOM_CORTO)) <> ''
    ORDER BY TXT_NOM_CORTO;
END;
GO
